linters:
  BemDepth:
    enabled: true
    max_elements: 2

  ColorKeyword:
    enabled: false

  ColorVariable:
    enabled: false

  DisableLinterReason:
    enabled: true

  DuplicateProperty:
    enabled: false

  ElsePlacement:
    enabled: true
    style: new_line

  EmptyLineBetweenBlocks:
    enabled: false

  ExtendDirective:
    enabled: true

  IdSelector:
    enabled: true

  ImportantRule:
    enabled: true

  LeadingZero:
    enabled: true
    style: include_zero

  NameFormat:
    enabled: true
    allow_leading_underscore: false
    convention: hyphenated_lowercase

  PropertySortOrder:
    enabled: true
    order: ["display", "visibility", "overflow", "overflow-x", "overflow-y", "clip", "zoom", "float", "clear", "flex-direction", "flex-order", "flex-pack", "flex-align", "position", "top", "right", "bottom", "left", "z-index", "box-sizing", "width", "min-width", "max-width", "height", "min-height", "max-height", "margin", "margin-top", "margin-right", "margin-bottom", "margin-left", "padding", "padding-top", "padding-right", "padding-bottom", "padding-left", "border", "border-width", "border-style", "border-color", "border-top", "border-top-width", "border-top-style", "border-top-color", "border-right", "border-right-width", "border-right-style", "border-right-color", "border-bottom", "border-bottom-width", "border-bottom-style", "border-bottom-color", "border-left", "border-left-width", "border-left-style", "border-left-color", "border-radius", "border-top-left-radius", "border-top-right-radius", "border-bottom-right-radius", "border-bottom-left-radius", "border-image", "border-image-source", "border-image-slice", "border-image-width", "border-image-outset", "border-image-repeat", "outline", "outline-width", "outline-style", "outline-color", "outline-offset", "table-layout", "empty-cells", "caption-side", "border-spacing", "border-collapse", "background", "filter:progid:DXImageTransform.Microsoft.AlphaImageLoader", "background-color", "background-image", "background-repeat", "background-attachment", "background-position", "background-position-x", "background-position-y", "background-clip", "background-origin", "background-size", "box-decoration-break", "box-shadow", "filter:progid:DXImageTransform.Microsoft.gradient", "color", "text-shadow", "opacity", "filter:progid:DXImageTransform.Microsoft.Alpha(Opacity", "list-style", "list-style-position", "list-style-type", "list-style-image", "content", "quotes", "counter-reset", "counter-increment", "resize", "cursor", "user-select", "nav-index", "nav-up", "nav-right", "nav-down", "nav-left", "text-align", "text-align-last", "vertical-align", "font", "font-family", "font-size", "line-height", "font-weight", "font-style", "font-variant", "font-size-adjust", "font-stretch", "font-effect", "font-emphasize", "font-emphasize-position", "font-emphasize-style", "font-smooth", "text-decoration", "white-space", "text-emphasis", "text-emphasis-color", "text-emphasis-style", "text-emphasis-position", "text-indent", "text-justify", "letter-spacing", "word-spacing", "text-outline", "text-transform", "text-wrap", "text-overflow", "text-overflow-ellipsis", "text-overflow-mode", "word-wrap", "word-break", "tab-size", "hyphens", "pointer-events", "transition", "transition-delay", "transition-timing-function", "transition-duration", "transition-property", "transform", "transform-origin", "animation", "animation-name", "animation-duration", "animation-play-state", "animation-timing-function", "animation-delay", "animation-iteration-count", "animation-direction"]
    ignore_unspecified: true

  PseudoElement:
    enabled: false

  SpaceAfterPropertyColon:
    enabled: true
    style: no_space
